---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config:
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    run_list:
      - recipe[ubuntu]
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[dhcp_net_setup]
    - recipe[dhcp::server]
  attributes:
    dhcp:
     groups: []
     hosts: all
     networks:
       - 192.168.9.0/24
     interfaces: 
       - 'lo:0'
     options:
       'domain-name': "vm"
       'domain-name-servers': 192.168.9.10
