---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config:
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[dhcp::server]
  attributes:
    dhcp:
     groups: []
     hosts: all
     networks:
       - 10.14.0.0/24
     options:
       domain-name: \"mgmt1 pod01\"
       domain-name-servers: 10.14.0.21

clusters:
  default:
    - default
