---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
- name: centos-6.6
- name: ubuntu-12.04
  run_list:
    - recipe[ubuntu]

suites:
- name: default
  run_list:
    - recipe[dhcp_net_setup::default]
    - recipe[dhcp::server]
    - recipe[testing::default]
  attributes:
    dhcp:
      interfaces:
        - eth0
        - eth1
      groups: []
      hosts: all
      networks:
        - 192.168.9.0/24
      shared_networks:
        - mysharednet
      options:
        domain-name: vm
        domain-name-servers: 192.168.9.1
      extra_files:
        - /var/tmp/extra1.conf
        - /var/tmp/extra2.conf

- name: no_bag
  run_list:
    - recipe[dhcp_net_setup::default]
    - recipe[dhcp_attributes::default]
    - recipe[dhcp::server]
  attributes:
    dhcp:
      interfaces:
        - eth0
        - eth1
      use_bags: false
      groups: []
      hosts: all
      networks:
        - 192.168.9.0/24
      options:
        domain-name: vm
        domain-name-servers: 192.168.9.1

- name: chef11
  provisioner:
    require_chef_omnibus: 11.18.6
  run_list:
    - recipe[dhcp_net_setup::default]
    - recipe[dhcp::server]
  attributes:
    dhcp:
      interfaces:
        - eth0
        - eth1
      groups: []
      hosts: all
      networks:
        - 192.168.9.0/24
      shared_networks:
        - mysharednet
      options:
        domain-name: vm
        domain-name-servers: 192.168.9.1
