---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-6.6
  attributes:
    dhcp:
      interfaces:
        - eth0
        - eth1
- name: ubuntu-12.04
  run_list:
    - recipe[ubuntu]
  attributes:
    dhcp:
      interfaces:
        - eth0
        - eth1

suites:
- name: default
  run_list:
    - recipe[dhcp_net_setup::default]
    - recipe[dhcp::server]
  attributes:
    dhcp:
      groups: []
      hosts: all
      networks:
        - 192.168.9.0/24
      shared_networks:
        - mysharednet
      options:
        domain-name: vm
        domain-name-servers: 192.168.9.1

- name: no_bag
  run_list:
    - recipe[dhcp_net_setup::default]
    - recipe[dhcp_attributes::default]
    - recipe[dhcp::server]
  attributes:
    dhcp:
     use_bags: false
     groups: []
     hosts: all
     networks:
       - 192.168.9.0/24
     options:
       domain-name: vm
       domain-name-servers: 192.168.9.1

- name: chef11
  provisioner:
    require_chef_omnibus: 11.18.6
  run_list:
    - recipe[dhcp_net_setup::default]
    - recipe[dhcp::server]
  attributes:
    dhcp:
      groups: []
      hosts: all
      networks:
        - 192.168.9.0/24
      shared_networks:
        - mysharednet
      options:
        domain-name: vm
        domain-name-servers: 192.168.9.1
